### ISSUE TITLE
improvement: make the SONG/SCORE processes cacheable

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/nextflow-data-processing-utility-tools#23]
based on my local testing, the song/score processes seem not cacheable, when resuming a failed / cancelled run, it always restarts from the very beginning of the workflow in which `song_get_analysis` is the first step.

tweaked the NF process code and tested locally, after the follow changes, basically avoid using dynamic `workflow.runName` in the `moutPath`, the processes become cacheable:
- pod secret: workflow.runName + "-secret", mountPath: "/tmp/" + workflow.**sessionId**
- accessToken = params.api_token ? params.api_token : "\`cat /tmp/${workflow.**sessionId**}/secret\`"

For some reason the `secret` part: `workflow.runName + "-secret"` does not work with `workflow.sessionId`. In my local runs it turns out I didn't need to change that part for it to work.

As this was not tested properly inside the K8S environment, it may not work there, so maybe not a properly solution but anything can be done to avoid using `workflow.runName` may help.

**Comment by rosibaj** [comment]
Deployed to Qa and testable!

**Comment by junjun-zhang** [comment]
addressed by #24, #25 and #26, basically `mountPath: "/tmp/rdpc_secret"` to make it stable. `sessionId` was not used because it's not available during run preparation step (before a run has been launched).

Tested in QA with expected behavious, ie, song/score steps are cacheable
